pages/learn/guides/worldbuilder/creating-glowing-materials.md
pages/learn/guides/worldbuilder/creating-your-first-world.md

What does this PR do?
- Fixes some typos in the two new docs

Nautis-TypoFixes

---

pages/learn/guides/_meta.json
pages/learn/guides/studio/Asset-Store/Uploading-to-the-Asset-Store.md
pages/learn/guides/studio/creating-your-first-world.md

Update World Builder -> Highrise Studio

Update World Builder -> Highrise Studio

---

content/en-us/reference/engine/classes/Behaviour.yaml
content/en-us/reference/engine/classes/Component.yaml
content/en-us/reference/engine/classes/GameObject.yaml
content/en-us/reference/engine/classes/Material.yaml
content/en-us/reference/engine/classes/Mesh.yaml
content/en-us/reference/engine/classes/MeshRenderer.yaml
content/en-us/reference/engine/classes/Object.yaml
content/en-us/reference/engine/classes/Renderer.yaml
content/en-us/reference/engine/classes/Texture.yaml
content/en-us/reference/engine/classes/Texture2D.yaml
content/en-us/reference/engine/classes/Texture3D.yaml
content/en-us/reference/engine/classes/Transform.yaml
content/en-us/reference/engine/classes/UIService.yaml
content/en-us/reference/engine/classes/UIView.yaml
content/en-us/reference/engine/classes/VisualElement.yaml
content/en-us/reference/engine/datatypes/Bounds.yaml
content/en-us/reference/engine/datatypes/Color.yaml
content/en-us/reference/engine/datatypes/Matrix4x4.yaml
content/en-us/reference/engine/datatypes/Quaternion.yaml
content/en-us/reference/engine/datatypes/Rect.yaml
content/en-us/reference/engine/datatypes/Vector2.yaml
content/en-us/reference/engine/datatypes/Vector3.yaml
content/en-us/reference/engine/datatypes/Vector4.yaml

- Copying the generated docs from the unity project into this repo
- Anything API related is auto inserted
- Anything UnityEngine links to external documentation if possible

First pass generation

---

pages/learn/engine-api/classes/Texture.yaml
pages/learn/engine-api/classes/UI.yaml
pages/learn/engine-api/classes/UIView.yaml

summaries instead of descriptions

Summaries instead of descriptions

---

pages/learn/studio-api/classes/Animator.yaml
pages/learn/studio-api/classes/AudioSource.yaml
pages/learn/studio-api/classes/Camera.yaml
pages/learn/studio-api/services/Mathf.yaml

more syntax

---

pages/learn/bots/guides/_meta.json
pages/learn/studio/guides/_meta.json

Fix capitalization

---

pages/learn/studio/guides/examples/multiplayer-button.md

Adds the Example doc for a Multiplayer Button

Multiplayer Button Example

---

pages/learn/studio/guides/examples/multiplayer-button.md

change numbered lists to bulleted

ConsistenBulletPointFormatting

---

pages/learn/studio/guides/scripting/scripting-a-gameobject.md

removed a typo from luau reference

---

pages/learn/studio/guides/scripting/scripting-a-gameobject.md

Fixed the DOCS link at the bottom

---

pages/learn/studio/guides/creating-your-first-world.md
pages/learn/studio/overview.md

Making updates from the user journey deck.
- Added link to scripting page from overview and your first game page.
- Added link to hub DL link in forums
- Added "search online" to asset store instructions
- Added practical description of navmesh functionality

Updated docs

---

pages/learn/studio/overview.md

Deleted erroneous .

---

pages/learn/studio/api/classes/AnimationEvent.yaml
pages/learn/studio/api/classes/AudioShader.yaml
pages/learn/studio/api/classes/ChannelInfo.yaml
pages/learn/studio/api/classes/Chat.yaml
pages/learn/studio/api/classes/Easing.yaml
pages/learn/studio/api/classes/Input.yaml
pages/learn/studio/api/classes/LongPressBeganEvent.yaml
pages/learn/studio/api/classes/LongPressContinueEvent.yaml
pages/learn/studio/api/classes/LongPressEndedEvent.yaml
pages/learn/studio/api/classes/LuaBindingsTest.yaml
pages/learn/studio/api/classes/LuaScript.yaml
pages/learn/studio/api/classes/Physics.yaml
pages/learn/studio/api/classes/PinchGestureBegan.yaml
pages/learn/studio/api/classes/PinchGestureChanged.yaml
pages/learn/studio/api/classes/PinchGestureEnded.yaml
pages/learn/studio/api/classes/Screen.yaml
pages/learn/studio/api/classes/TapEvent.yaml
pages/learn/studio/api/classes/TapHandler.yaml
pages/learn/studio/api/classes/UI.yaml
pages/learn/studio/api/classes/UIView.yaml
pages/learn/studio/api/classes/VisualElement.yaml
pages/learn/studio/api/classes/WorldScene.yaml
pages/learn/studio/api/datatypes/Mathf.yaml
pages/learn/studio/api/services/Input.yaml

Updates Lua API docs with correct casing for properties and fields.
Adds stubs for some missing classes.

update lua properties and fields with camel case

---

pages/learn/studio/guides/scripting/_meta.json
pages/learn/studio/guides/scripting/client-and-server-scripts.md
pages/learn/studio/guides/scripting/network-values.md
pages/learn/studio/guides/scripting/player-character-events.md
pages/learn/studio/guides/scripting/server-values.md
pages/learn/studio/guides/scripting/taphandlers.md
pages/learn/studio/guides/scripting/triggers.md

New Scripting Doc Pages
- Triggers
- TapHanlder
- Client and Server Lua
- Client/Server/Player/Scene Events
- Server Values

Scripting Docs

---

pages/learn/studio/guides/Asset-Store/_meta.json
pages/learn/studio/guides/_meta.json
pages/learn/studio/guides/creating-your-first-world-2.md
pages/learn/studio/guides/creating-your-first-world.md

Update creating your first world

---

pages/learn/studio/guides/creating-your-first-world.md

Fix numbering

---

pages/learn/studio/guides/creating-your-first-world.md

Remove part 1

---

pages/learn/studio/guides/publishing-world.md

Update publishing doc

---

pages/learn/studio/guides/scripting/gameobjects-and-components.md

newObjectTransform vs newObjectTran Guide Fix

---

pages/learn/studio/guides/scripting/serialized-fields.md

Fixing typos and grammatic errors
This is a tutorial on how to open a pull request

updating typos in serialized-fields

---

pages/learn/studio/guides/_meta.json
pages/learn/studio/guides/game-development/_meta.json
pages/learn/studio/guides/game-development/particles.md

Add particle guide

---

pages/learn/studio/guides/game-development/particles.md

Fix youtube link

---

pages/learn/studio/guides/_meta.json
pages/learn/studio/guides/collaboration/_meta.json
pages/learn/studio/guides/collaboration/github.md

Add github guide

---

pages/learn/studio/guides/_meta.json

Reorder docs

---

pages/learn/studio/guides/collaboration/_meta.json
pages/learn/studio/guides/collaboration/docs.md
pages/learn/studio/guides/intro-game-dev/particles.md

A new guide page to teach people how to collaborate directly from GitHub or locally, with a video tutorial.
People who want to collaborate and edit but are new to this stuff.

New guide on how to collaborate

---

README.md
STYLE.md

update README and add style guide

---

pages/learn/studio/guides/3d-modeling-and-animation/Box-Modelling-an-Asset.md

Update box modelling doc with style guide

---

pages/learn/studio/guides/creating-glowing-materials.md
pages/learn/studio/guides/downloading-assets.md
pages/learn/studio/guides/importing-world.md
pages/learn/studio/guides/publishing-world.md

update some guides

---

pages/learn/studio/guides/creating-your-first-world.md

Update creating first world guide

---

pages/learn/studio/guides/examples/multiplayer-button.md

Update multiplayer button

---

pages/learn/studio/guides/_meta.json

organization

---

pages/learn/studio/create/_meta.json
pages/learn/studio/create/examples/worlds/_meta.json

minor fixes

---

pages/learn/studio/create/_meta.json
pages/learn/studio/create/ui/_meta.json
pages/learn/studio/create/ui/overview.md

Add UI Overview placeholder

---

pages/learn/studio/api/classes/Player.yaml
pages/learn/studio/api/classes/UI.yaml

It fixes a few mistakes in the previous PR that added the studio API docs for 0.6.8

Fix studio API docs for 0.6.8

---

pages/learn/studio/create/ui/_meta.json
pages/learn/studio/create/ui/creating-your-first-ui.md

Nautis examples

---

pages/learn/studio/create/ui/_meta.json
pages/learn/studio/create/ui/creating-your-first-ui.md
pages/learn/studio/create/ui/custom-fonts.md

customFontsDoc

---

pages/learn/studio/create/examples/components/_meta.json
pages/learn/studio/create/examples/components/multiplayer-button.md
pages/learn/studio/create/examples/components/multiplayer-nav-gate.md
pages/learn/studio/create/examples/components/multiplayer-number-generator.md
pages/learn/studio/create/examples/components/teleport-players.md

teleportPlayers Doc

---

pages/learn/studio/create/examples/components/_meta.json
pages/learn/studio/create/examples/components/tracking-players.md

tracking players module

---

pages/learn/studio/api/classes/InventoryError.yaml
pages/learn/studio/api/classes/InventoryItem.yaml
pages/learn/studio/api/classes/InventoryReservation.yaml
pages/learn/studio/api/classes/InventoryTransaction.yaml
pages/learn/studio/api/classes/StorageError.yaml
pages/learn/studio/api/services/Inventory.yaml
pages/learn/studio/api/services/Storage.yaml

- Adds docs for persistence API

Persistence API Docs

---

pages/learn/studio/create/environment/lighting/types-of-light/directional-light.md
pages/learn/studio/create/environment/lighting/types-of-light/point-light.md
pages/learn/studio/create/environment/lighting/types-of-light/spot-light.md
pages/learn/studio/create/scripting/lua/overview.md

Fixed broken images

---

pages/learn/studio/api/datatypes/Color.yaml
pages/learn/studio/api/datatypes/Vector3.yaml
pages/learn/studio/api/globals.yaml
pages/learn/studio/api/services/Chat.yaml
pages/learn/studio/api/services/Input.yaml
pages/learn/studio/api/services/Storage.yaml
pages/learn/studio/create/scripting/advanced/triggers.md

Fixed indentation errors in YAML files that were causing YAML not to load properly.

Fixed indentation errors in YAML files

---

pages/learn/studio/api/datatypes/RaycastHit.yaml
pages/learn/studio/api/datatypes/Rect.yaml
pages/learn/studio/api/datatypes/Tween.yaml
pages/learn/studio/api/datatypes/Vector2.yaml
pages/learn/studio/api/datatypes/Vector4.yaml
pages/learn/studio/create/_meta.json
pages/learn/studio/create/characters/_meta.json
pages/learn/studio/create/characters/overview.md
pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/leaderboard.md
pages/learn/studio/create/ui/creating-your-first-ui.md
pages/learn/studio/resources/_meta.json
pages/learn/studio/resources/game-jam.md
pages/learn/studio/resources/meet-the-creators.md

- Edited the game jam to match the new ones
- Provided a better UI example for starters
- Persistent leaderboard with scores
- Datatypes better summary & more examples
- Characters section, including NPCs (to be updated)
- Creators feedback section to highlight interviews with creators

Better examples

---

pages/learn/studio/api/datatypes/Quaternion.yaml
pages/learn/studio/api/datatypes/Ray.yaml
pages/learn/studio/api/services/Mathf.yaml
pages/learn/studio/api/services/Physics.yaml
pages/learn/studio/api/services/Screen.yaml
pages/learn/studio/api/services/Time.yaml
pages/learn/studio/create/assets/_meta.json
pages/learn/studio/create/assets/uploading-assets.md
pages/learn/studio/resources/meet-the-creators.md

- Fixed a typo in "Meet the Creators" (requested by the creator)
- Added a new page for uploading assets to the Highrise Assets Catalog
- Added more examples for both data types and services in the API section
- Updated some old methods that are no longer usable

Added new pages, updated old methods, and added more examples in the API section

---

pages/learn/studio/api/services/Payments.yaml

Fixed TypeError: e.returns.map is not a function in Payments.yaml

Fixed TypeError: e.returns.map is not a function

---

pages/learn/studio/api/classes/AudioShader.yaml
pages/learn/studio/api/classes/Character.yaml
pages/learn/studio/api/classes/Sounds.yaml
pages/learn/studio/api/classes/TapHandler.yaml
pages/learn/studio/api/classes/VisualElement.yaml
pages/learn/studio/api/services/Chat.yaml
pages/learn/studio/api/services/Easing.yaml
pages/learn/studio/api/services/Input.yaml
pages/learn/studio/create/scripting/advanced/unity-functions.md

- Reworked the entire Visual Element page (removed all Unity references)
- Fixed broken image URLs
- Added the missing character methods for outfits with examples
- Added examples for the Chat class
- Added examples for the Easing class
- Added examples for the Input class
- Reworked the Audio shader to include/remove methods with examples
- Added examples for Sounds
- Improved the summary for TapHandlers with examples

Hsein update

---

pages/learn/studio/create/scripting/lua/attributes/serialized-fields.md
pages/learn/studio/create/scripting/lua/attributes/typings.md
pages/learn/studio/create/scripting/lua/overview.md
pages/learn/studio/create/scripting/overview.md
pages/learn/studio/create/ui/custom-fonts.md
pages/learn/studio/distribute/monetization/accepting-gold.md
pages/learn/studio/distribute/monetization/earning-overview.md

- Added Lua code academy courses.
- Fixed serialized fields examples.
- Modified script types, as they are now required.
- Added custom variables examples to USS.
- Added links to free courses.
- Highrise Payments API distribution.
- Refinement for the distribution.

Refinement for the distribution in Highrise

---

pages/learn/studio/api/classes/Anchor.yaml
pages/learn/studio/create/chat/voice.md
pages/learn/studio/create/environment/_meta.json
pages/learn/studio/create/environment/anchor.md
pages/learn/studio/create/environment/jump.md
pages/learn/studio/create/environment/post-processing.md
pages/learn/studio/create/ui/_meta.json
pages/learn/studio/create/ui/responsive-ui.md
pages/learn/studio/distribute/monetization/accepting-gold.md

- Added anchor examples
- Added jump examples
- Instructions on where to find earned gold after receiving gold payments
- Voice API documentation
I might need to update some of the information to include chat and channel info properties and methods.

Anchors, Jump & Voice API

---

pages/learn/studio/resources/meet-the-creators.md

Meet the Creators your.moth & its.gr - Creator of *Street Rave*

World Creator Spotlight Interview

---

pages/learn/studio/api/services/Payments.yaml
pages/learn/studio/create/scripting/advanced/payments.md

Renamed **World Products** to **In-World Purchases (IWP)**

Renamed "World Products' to "In-World Purchases (IWP)"

---

pages/learn/studio/distribute/monetization/_meta.json
pages/learn/studio/distribute/monetization/in-world-purchases.md
pages/learn/studio/distribute/monetization/world-wallet.md

- Added World Wallet
- In-World Purchases

World Wallet & IWP

---

pages/learn/studio/distribute/publishing-asset.md

Added steps on how to price the assets.

Pricing Assets

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/transferring-gold.md
pages/learn/studio/create/scripting/lua/best-practices/_meta.json
pages/learn/studio/create/scripting/lua/best-practices/security.md

- Added security measures for best practices
- Added examples of how to use the world wallet (server-side only)
- Provided a link to best practices for avoiding security breaches
Note: The security page will be updated; this is a preliminary version to make it live on the creator portal.

World Wallet & Security Management

---

pages/learn/studio/distribute/_meta.json
pages/learn/studio/distribute/advertising/_meta.json
pages/learn/studio/distribute/advertising/world-advertisements.md

Added a new section for advertisements under Distributing:
- World Advertisements:
- Introduction
- How to Create and Manage Your Campaign
- Campaign Budget
- Campaign Budget Tips
- Analytics

World Advertisements

---

pages/learn/studio/create/characters/overview.md
pages/learn/studio/create/scripting/lua/overview.md

- Added a link to the Security Best Practices in the Lua overview
- Updated the method for creating NPCs and outfits

NPC Updates

---

pages/learn/studio/create/ui/_meta.json
pages/learn/studio/create/ui/creating-your-first-ui.md
pages/learn/studio/create/ui/custom-fonts.md
pages/learn/studio/create/ui/custom-icons.md
pages/learn/studio/create/ui/overview.md
pages/learn/studio/create/ui/responsive-ui.md
pages/learn/studio/create/ui/ui-toolkit-debugger.md
pages/learn/studio/create/ui/variables.md

- Added instructions for variables
- Added custom fonts
- Added custom icons
- How to use the UI Toolkit Debugger
- Minor fixes and updates to existing pages

Improved UI documentation

---

pages/learn/studio/distribute/_meta.json
pages/learn/studio/distribute/highrise-assets-catalog-policy.md
pages/learn/studio/resources/_meta.json

- Remove outdated Game Jam page
- Added Highrise Assets Catalog Policy

Highrise Assets Catalog Policy

---

pages/learn/studio/distribute/advertising/world-advertisements.md

- Created a form to request Ad Credits
- Link to the form from the World Advertisements page

Added Ad Credit Request Form

---

pages/learn/studio/create/characters/_meta.json
pages/learn/studio/create/characters/controllers/_meta.json
pages/learn/studio/create/characters/controllers/joystick.md

- Added Instructions on how to use Joysticks
- Considerations when using Joysticks
- Sub section for different controllers

Joystick - How to use

---

pages/learn/studio/resources/meet-the-creators.md

Meet the creators Tounni & Community

Meet the creators Tounni & Community

---

pages/learn/studio/create/scripting/script-types/module.md

- Better module scripts documentation

Fixed module scripts

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/inventory.md
pages/learn/studio/create/scripting/advanced/matchmaking.md

- Matchmaking API Examples
- Inventory Usage

Added Matchmaking & Inventory Examples

---

pages/learn/studio/create/scripting/advanced/payments.md

- Fixed missing examples
- Added "How to Create IWP for Payments"
- Server & Client Side (How to use)

Better "Payments" examples

---

pages/learn/studio/create/scripting/advanced/payments.md

World owner cannot purchase their own IWPs

Added missing notes for Payments

---

pages/learn/studio/resources/meet-the-creators.md

Drewsifer's "Open Mic Night" interview

Creator Spotlight Update

---

pages/learn/studio/create/scripting/advanced/network-values.md

New network value: `TableValue`

Added TableValue to Network values

---

pages/learn/studio/create/scripting/lua/attributes/serialized-fields.md

- We don't support runtime
- Emphasizes key uses for Serialized Fields
- Adding missing types like Tables

Added Missing Serialized Field Types

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/hrpluscheck.md

Add examples on how to validate a HR+ subscriber

HR+ Validation

---

pages/learn/studio/create/scripting/advanced/timers.md

How to stop and clear an active timer

Added interval examples

---

pages/learn/studio/create/scripting/advanced/transferring-gold.md

TransferGoldToPlayer is not supported on client side

Fixed TransferGoldToPlayer examples

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/localization.md

- Adding Localizable Text
- Adding Languages
- Using Localized Text in Your World

Added localization

---

pages/learn/studio/create/characters/_meta.json
pages/learn/studio/create/characters/outfits.md

- Examples on how to create a new outfit.
- Examples on how to equip/unequip an outfit.
- Examples on how to store and handle outfits in a module script.

Add guides for changing character outfits

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/deeplinks.md

- What are deeplinks
- How to use deeplinks
- Different deeplinks examples

Add guides on deeplinks: overview, usage, and examples

---

pages/learn/studio/create/characters/overview.md

Fixed how to create an NPC outfit

Fixed NPC guides

---

pages/learn/studio/create/examples/worlds/dress-up-npc/overview.md

Added invitation link to visit the world in app

Link to visit the world in app

---

pages/learn/studio/create/scripting/advanced/transferring-gold.md

- Added Error Codes to the "transfer-gold" guide.

Added WalletError codes

---

pages/learn/studio/basics/getting-started.md
pages/learn/studio/distribute/publishing-asset.md
pages/learn/studio/distribute/publishing-world.md

- Added new guides on how to:
- Publish Assets
- Publish Worlds
- Upload Worlds

Updated Worlds & Assets Publish Flow

---

pages/learn/studio/basics/beginner-guide/_meta.json
pages/learn/studio/basics/beginner-guide/lecture-four/_meta.json

- Changed page numbers from text to numeric format.

Fixed the order of pages

---

pages/learn/studio/create/_meta.json
pages/learn/studio/create/environment/anchor.md
pages/learn/studio/create/environment/jump.md
pages/learn/studio/create/environment/navmesh.md

- Updated guides on Anchors, Jump Points & NavMesh
- Removed outdated Cloud documentation to replace it with Storage examples

Updated Guides

---

pages/learn/studio/basics/getting-started.md
pages/learn/studio/create/assets/overview.md
pages/learn/studio/create/beginner-guide/lecture-four/lecture-four-part-one.md
pages/learn/studio/create/beginner-guide/lecture-four/lecture-four-part-three.md
pages/learn/studio/create/beginner-guide/lecture-four/lecture-four-part-two.md
pages/learn/studio/create/beginner-guide/lecture-one.md
pages/learn/studio/create/beginner-guide/lecture-three.md
pages/learn/studio/create/beginner-guide/lecture-two.md
pages/learn/studio/create/scripting/writing-your-first-script.md

- Added a link to the new lectures on YouTube.
- Removed outdated links from older guides.

Updated YouTube links

---

pages/learn/studio/create/beginner-guide/lecture-five.md
pages/learn/studio/create/beginner-guide/lecture-four/lecture-four-part-five.md
pages/learn/studio/create/beginner-guide/lecture-four/lecture-four-part-four.md

- Added tutorial videos to:
- Lecture Four Part 4 (Scripts)
- Lecture Four Part 5 (Scenes)
- Lecture 5 (Importing assets)

Added Tutorial Videos

---

pages/learn/studio/create/beginner-guide/lecture-eight.md
pages/learn/studio/create/beginner-guide/lecture-seven.md
pages/learn/studio/create/beginner-guide/lecture-six.md

- Added YouTube links to:
- Lecture 6: NavMesh
- Lecture 7: Jump Points
- Lecture 8: Anchor Points

Link to YouTube tutorials

---

pages/learn/studio/resources/_meta.json

- Removed meet the creator section from resources

Removed "Meet the creator" section

---

pages/learn/studio/create/beginner-guide/lecture-nine.md

Added link to Lecture 9 YouTube video

Lecture 9 Tutorial Video

---

pages/learn/studio/create/environment/anchor.md
pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/client-server-communication.md

- Moved "Client-Server Communication" before "Network Values"
- Added keyword "sit" to anchors for easier search

Reorganized the pages

---

pages/learn/studio-api/datatypes/Angle.yaml
pages/learn/studio-api/datatypes/AnimatorStateInfo.yaml
pages/learn/studio-api/datatypes/BackgroundPosition.yaml
pages/learn/studio-api/datatypes/BackgroundRepeat.yaml
pages/learn/studio-api/datatypes/BackgroundSize.yaml
pages/learn/studio-api/datatypes/ContactPoint.yaml
pages/learn/studio-api/datatypes/Length.yaml
pages/learn/studio-api/datatypes/LocalizedString.yaml
pages/learn/studio-api/datatypes/NavMeshHit.yaml
pages/learn/studio-api/datatypes/Rotate.yaml
pages/learn/studio-api/datatypes/Scale.yaml
pages/learn/studio-api/datatypes/StyleBackgroundPosition.yaml
pages/learn/studio-api/datatypes/StyleBackgroundRepeat.yaml
pages/learn/studio-api/datatypes/StyleBackgroundSize.yaml
pages/learn/studio-api/datatypes/StyleColor.yaml
pages/learn/studio-api/datatypes/StyleFloat.yaml
pages/learn/studio-api/datatypes/StyleInt.yaml
pages/learn/studio-api/datatypes/StyleLength.yaml
pages/learn/studio-api/datatypes/StyleRotate.yaml
pages/learn/studio-api/datatypes/StyleScale.yaml
pages/learn/studio-api/datatypes/StyleTextShadow.yaml
pages/learn/studio-api/datatypes/StyleTransformOrigin.yaml
pages/learn/studio-api/datatypes/StyleTranslate.yaml
pages/learn/studio-api/datatypes/TextShadow.yaml
pages/learn/studio-api/datatypes/TransformOrigin.yaml
pages/learn/studio-api/datatypes/Translate.yaml

- Added 26 missing datatypes
- Angle.yaml
- AnimatorStateInfo.yaml
- BackgroundPosition.yaml
- BackgroundRepeat.yaml
- BackgroundSize.yaml
- ContactPoint.yaml
- Length.yaml
- LocalizedString.yaml
- NavMeshHit.yaml
- Rotate.yaml
- Scale.yaml
- StyleBackgroundPosition.yaml
- StyleBackgroundRepeat.yaml
- StyleBackgroundSize.yaml
- StyleColor.yaml
- StyleFloat.yaml
- StyleInt.yaml
- StyleLength.yaml
- StyleRotate.yaml
- StyleScale.yaml
- StyleTextShadow.yaml
- StyleTransformOrigin.yaml
- StyleTranslate.yaml
- TextShadow.yaml
- TransformOrigin.yaml
- Translate.yaml

Added 26 missing datatypes

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/moderation.md

Added moderation API guides

---

pages/learn/studio/create/beginner-guide/lecture-fourteen.md
pages/learn/studio/create/beginner-guide/lecture-thirteen.md
pages/learn/studio/create/projects/teams/github.md

- Added tutorial videos to:\
- Lecture 13
- Lecture 14
- Lecture Work in Teams

Tutorial Videos

---

pages/learn/studio-api/classes/Character.yaml
pages/learn/studio/create/scripting/advanced/gameobjects-and-components.md
pages/learn/studio/create/scripting/lua/attributes/serialized-fields.md
pages/learn/studio/resources/_meta.json
pages/learn/studio/resources/game-jam-rules.md

Fixed studio examples

---

pages/learn/studio/create/ui/creating-your-first-ui.md
pages/learn/studio/resources/game-jam-rules.md

Modified Game Jam Rules

---

pages/learn/studio-api/classes/AttachToPanelEvent.yaml
pages/learn/studio-api/classes/BindableElement.yaml
pages/learn/studio-api/classes/BlurEvent.yaml
pages/learn/studio-api/classes/Button.yaml
pages/learn/studio-api/classes/DetachFromPanelEvent.yaml
pages/learn/studio-api/classes/Enum.yaml
pages/learn/studio-api/classes/FocusEvent.yaml
pages/learn/studio-api/classes/FocusInEvent.yaml
pages/learn/studio-api/classes/FocusOutEvent.yaml
pages/learn/studio-api/classes/Gradient.yaml
pages/learn/studio-api/classes/IStyle.yaml
pages/learn/studio-api/classes/Image.yaml
pages/learn/studio-api/classes/Input.yaml
pages/learn/studio-api/classes/InputAction.yaml
pages/learn/studio-api/classes/InputActionMap.yaml
pages/learn/studio-api/classes/InputActionReference.yaml
pages/learn/studio-api/classes/InputEvent.yaml
pages/learn/studio-api/classes/Label.yaml
pages/learn/studio-api/classes/Motion.yaml
pages/learn/studio-api/classes/NavMesh.yaml
pages/learn/studio-api/classes/NavMeshAgent.yaml
pages/learn/studio-api/classes/NavMeshObstacle.yaml
pages/learn/studio-api/classes/NavMeshSurface.yaml
pages/learn/studio-api/classes/NetworkBehaviour.yaml
pages/learn/studio-api/classes/TransitionCancelEvent.yaml
pages/learn/studio-api/classes/TransitionEndEvent.yaml
pages/learn/studio-api/classes/TransitionRunEvent.yaml
pages/learn/studio-api/classes/TransitionStartEvent.yaml
pages/learn/studio-api/classes/WheelEvent.yaml
pages/learn/studio/create/scripting/advanced/payments.md

Added missing links

---

pages/learn/studio/create/beginner-guide/_meta.json
pages/learn/studio/create/beginner-guide/lecture-sixteen.md

Added new lectutre

---

pages/learn/studio/create/coding-fundamentals/overview.md

VS Code Extention

---

pages/learn/studio/create/scripting/advanced/_meta.json
pages/learn/studio/create/scripting/advanced/world-persistence-api.md

Highrise World Persistence API

---

pages/learn/studio/create/beginner-guide/_meta.json
pages/learn/studio/create/beginner-guide/lecture-seventeen.md

Lecture 17: Character Controller

---

pages/learn/studio/resources/game-jam-rules.md

New game jam rules

---

pages/learn/studio/create/ui/_meta.json

Update _meta.json for User Interface

---

pages/learn/studio/create/scripting/advanced/localization.md

Better localization guides

---

pages/learn/studio-api/enums/Align.yaml
pages/learn/studio-api/enums/AngleUnit.yaml
pages/learn/studio-api/enums/BackgroundPositionKeyword.yaml
pages/learn/studio-api/enums/BackgroundSizeType.yaml
pages/learn/studio-api/enums/CharacterState.yaml
pages/learn/studio-api/enums/DisplayStyle.yaml
pages/learn/studio-api/enums/FlexDirection.yaml
pages/learn/studio-api/enums/FontStyle.yaml
pages/learn/studio-api/enums/ForceMode.yaml
pages/learn/studio-api/enums/Justify.yaml
pages/learn/studio-api/enums/Overflow.yaml
pages/learn/studio-api/enums/OverflowClipBox.yaml
pages/learn/studio-api/enums/PickingMode.yaml
pages/learn/studio-api/enums/Position.yaml
pages/learn/studio-api/enums/PressEffect.yaml
pages/learn/studio-api/enums/Repeat.yaml
pages/learn/studio-api/enums/Space.yaml
pages/learn/studio-api/enums/StyleKeyword.yaml
pages/learn/studio-api/enums/TextAnchor.yaml
pages/learn/studio-api/enums/TextOverflow.yaml
pages/learn/studio-api/enums/TextOverflowPosition.yaml
pages/learn/studio-api/enums/TrickleDown.yaml
pages/learn/studio-api/enums/Visibility.yaml
pages/learn/studio-api/enums/WhiteSpace.yaml
pages/learn/studio-api/enums/Wrap.yaml

add enums folder

---

pages/learn/host-resources/_meta.json
pages/learn/host-resources/hrstream/_meta.json
pages/learn/host-resources/hrstream/guidelines.md

- Added HR Stream partner guidelines document

Added HR Stream Partner Guidelines
